Halide: Halide::Buffer Class Reference
Halide::Buffer Class Reference
The internal representation of an image, or other dense array data.
#include <Buffer.h>
Public Member Functions
Buffer ()
Buffer (Type t, int x_size=0, int y_size=0, int z_size=0, int w_size=0, uint8_t *data=NULL)
Buffer (Type t, const buffer_t *buf)
void * host_ptr () const
Get a pointer to the host-side memory.
buffer_t * raw_buffer () const
Get a pointer to the raw buffer_t struct that this class wraps.
uint64_t device_handle () const
Get the device-side pointer/handle for this buffer.
bool host_dirty () const
Has this buffer been modified on the cpu since last copied to a device.
void set_host_dirty (bool dirty=true)
Let Halide know that the host-side memory backing this buffer has been externally modified.
bool device_dirty () const
Has this buffer been modified on device since last copied to the cpu.
void set_device_dirty (bool dirty=true)
Let Halide know that the device-side memory backing this buffer has been externally modified, and so the cpu-side memory is invalid.
int dimensions () const
Get the dimensionality of this buffer.
int extent (int dim) const
Get the extent of this buffer in the given dimension.
int stride (int dim) const
Get the number of bytes between adjacent elements of this buffer along the given dimension.
int min (int dim) const
Get the coordinate in the function that this buffer represents that corresponds to the base address of the buffer.
Type type () const
Get the Halide type of the contents of this buffer.
bool same_as (const Buffer &other) const
Compare two buffers for identity (not equality of data).
bool defined () const
Check if this buffer handle actually points to data.
const std::string & name () const
Get the runtime name of this buffer used for debugging.
operator Argument () const
Convert this buffer to an argument to a halide pipeline.
void set_source_module (const Internal::JITCompiledModule &module)
Declare that this buffer was created by the given jit-compiled module.
const Internal::JITCompiledModule & source_module ()
If this buffer was the output of a jit-compiled realization, retrieve the module it came from.
void copy_to_host ()
If this buffer was created on-device by a jit-compiled realization, then copy it back to the cpu-side memory.
void copy_to_dev ()
If this buffer was created by a jit-compiled realization on a device-aware target (e.g.
void free_dev_buffer ()
If this buffer was created by a jit-compiled realization on a device-aware target (e.g.
Detailed Description
The internal representation of an image, or other dense array data.
The Image type provides a typed view onto a buffer for the purposes of direct manipulation. A buffer may be stored in main memory, or some other memory space (e.g. a gpu). If you want to use this as an Image, see the Image class. Casting a Buffer to an Image will do any appropriate copy-back. This class is a fairly thin wrapper on a buffer_t, which is the C-style type Halide uses for passing buffers around.
Definition at line 100 of file Buffer.h.
Constructor & Destructor Documentation
Halide::Buffer::Buffer () inline
Definition at line 104 of file Buffer.h.
Halide::Buffer::Buffer (Type t, int x_size = 0, int y_size = 0, int z_size = 0, int w_size = 0, uint8_t * data = NULL) inline
Definition at line 106 of file Buffer.h.
Halide::Buffer::Buffer (Type t, const buffer_t * buf) inline
Definition at line 111 of file Buffer.h.
Member Function Documentation
void* Halide::Buffer::host_ptr () const inline
Get a pointer to the host-side memory.
Definition at line 116 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), buffer_t::host, and Halide::Internal::IntrusivePtr< T >::ptr.
buffer_t* Halide::Buffer::raw_buffer () const inline
Get a pointer to the raw buffer_t struct that this class wraps.
Definition at line 122 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), and Halide::Internal::IntrusivePtr< T >::ptr.
Referenced by copy_to_dev(), copy_to_host(), free_dev_buffer(), and Halide::Image< T >::operator const buffer_t *().
uint64_t Halide::Buffer::device_handle () const inline
Get the device-side pointer/handle for this buffer.
Will be zero if no device was involved in the creation of this buffer.
Definition at line 130 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), buffer_t::dev, and Halide::Internal::IntrusivePtr< T >::ptr.
bool Halide::Buffer::host_dirty () const inline
Has this buffer been modified on the cpu since last copied to a device.
Not meaningful unless there's a device involved.
Definition at line 137 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), buffer_t::host_dirty, and Halide::Internal::IntrusivePtr< T >::ptr.
void Halide::Buffer::set_host_dirty (bool dirty = true) inline
Let Halide know that the host-side memory backing this buffer has been externally modified.
You shouldn't normally need to call this, because it is done for you when you cast a Buffer to an Image in order to modify it.
Definition at line 146 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), buffer_t::host_dirty, and Halide::Internal::IntrusivePtr< T >::ptr.
Referenced by Halide::Image< T >::set_host_dirty().
bool Halide::Buffer::device_dirty () const inline
Has this buffer been modified on device since last copied to the cpu.
Not meaninful unless there's a device involved.
Definition at line 153 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), buffer_t::dev_dirty, and Halide::Internal::IntrusivePtr< T >::ptr.
void Halide::Buffer::set_device_dirty (bool dirty = true) inline
Let Halide know that the device-side memory backing this buffer has been externally modified, and so the cpu-side memory is invalid.
A copy-back will occur the next time you cast this Buffer to an Image, or the next time this buffer is accessed on the host in a halide pipeline.
Definition at line 163 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), buffer_t::host_dirty, and Halide::Internal::IntrusivePtr< T >::ptr.
int Halide::Buffer::dimensions () const inline
Get the dimensionality of this buffer.
Uses the convention that the extent field of a buffer_t should contain zero when the dimensions end.
Definition at line 171 of file Buffer.h.
References extent().
int Halide::Buffer::extent (int dim) const inline
Get the extent of this buffer in the given dimension.
Definition at line 179 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), buffer_t::extent, and Halide::Internal::IntrusivePtr< T >::ptr.
Referenced by dimensions(), and Halide::Image< T >::extent().
int Halide::Buffer::stride (int dim) const inline
Get the number of bytes between adjacent elements of this buffer along the given dimension.
Definition at line 186 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), Halide::Internal::IntrusivePtr< T >::ptr, and buffer_t::stride.
Referenced by Halide::Image< T >::stride().
int Halide::Buffer::min (int dim) const inline
Get the coordinate in the function that this buffer represents that corresponds to the base address of the buffer.
Definition at line 194 of file Buffer.h.
References Halide::Internal::BufferContents::buf, defined(), buffer_t::min, and Halide::Internal::IntrusivePtr< T >::ptr.
Type Halide::Buffer::type () const inline
Get the Halide type of the contents of this buffer.
Definition at line 201 of file Buffer.h.
References defined(), Halide::Internal::IntrusivePtr< T >::ptr, and Halide::Internal::BufferContents::type.
Referenced by Halide::Internal::Call::make(), operator Argument(), and Halide::Internal::Parameter::set_buffer().
bool Halide::Buffer::same_as (const Buffer & other) const inline
Compare two buffers for identity (not equality of data).
Definition at line 207 of file Buffer.h.
References Halide::Internal::IntrusivePtr< T >::same_as().
bool Halide::Buffer::defined () const inline
Check if this buffer handle actually points to data.
Definition at line 212 of file Buffer.h.
References Halide::Internal::IntrusivePtr< T >::defined().
Referenced by Halide::Image< T >::defined(), device_dirty(), device_handle(), extent(), host_dirty(), host_ptr(), Halide::Internal::Call::make(), min(), raw_buffer(), Halide::Internal::Parameter::set_buffer(), set_device_dirty(), set_host_dirty(), set_source_module(), source_module(), stride(), and type().
const std::string& Halide::Buffer::name () const inline
Get the runtime name of this buffer used for debugging.
Definition at line 217 of file Buffer.h.
References Halide::Internal::BufferContents::name, and Halide::Internal::IntrusivePtr< T >::ptr.
Referenced by Halide::Internal::Call::make(), and operator Argument().
Halide::Buffer::operator Argument () const inline
Convert this buffer to an argument to a halide pipeline.
Definition at line 222 of file Buffer.h.
References name(), and type().
void Halide::Buffer::set_source_module (const Internal::JITCompiledModule & module) inline
Declare that this buffer was created by the given jit-compiled module.
Used internally for reference counting the module.
Definition at line 228 of file Buffer.h.
References defined(), Halide::Internal::IntrusivePtr< T >::ptr, and Halide::Internal::BufferContents::source_module.
const Internal::JITCompiledModule& Halide::Buffer::source_module () inline
If this buffer was the output of a jit-compiled realization, retrieve the module it came from.
Otherwise returns a module struct full of null pointers.
Definition at line 236 of file Buffer.h.
References defined(), Halide::Internal::IntrusivePtr< T >::ptr, and Halide::Internal::BufferContents::source_module.
void Halide::Buffer::copy_to_host () inline
If this buffer was created on-device by a jit-compiled realization, then copy it back to the cpu-side memory.
This is usually achieved by casting the Buffer to an Image.
Definition at line 244 of file Buffer.h.
References Halide::Internal::JITCompiledModule::copy_to_host, Halide::Internal::IntrusivePtr< T >::ptr, raw_buffer(), and Halide::Internal::BufferContents::source_module.
Referenced by Halide::Image< T >::copy_to_host().
void Halide::Buffer::copy_to_dev () inline
If this buffer was created by a jit-compiled realization on a device-aware target (e.g.
PTX), then copy the cpu-side data to the device-side allocation. TODO: I believe this currently aborts messily if no device-side allocation exists. You might think you want to do this because you've modified the data manually on the host before calling another Halide pipeline, but what you actually want to do in that situation is set the host_dirty bit so that Halide can manage the copy lazily for you. Casting the Buffer to an Image sets the dirty bit for you.
Definition at line 262 of file Buffer.h.
References Halide::Internal::JITCompiledModule::copy_to_dev, Halide::Internal::IntrusivePtr< T >::ptr, raw_buffer(), and Halide::Internal::BufferContents::source_module.
void Halide::Buffer::free_dev_buffer () inline
If this buffer was created by a jit-compiled realization on a device-aware target (e.g.
PTX), then free the device-side allocation, if there is one. Done automatically when the last reference to this buffer dies.
Definition at line 274 of file Buffer.h.
References Halide::Internal::JITCompiledModule::free_dev_buffer, Halide::Internal::IntrusivePtr< T >::ptr, raw_buffer(), and Halide::Internal::BufferContents::source_module.
The documentation for this class was generated from the following file:
Buffer.h