Halide: Halide::Internal::Parameter Class Reference
Halide::Internal::Parameter Class Reference
A reference-counted handle to a parameter to a halide pipeline.
#include <Parameter.h>
Public Member Functions
Parameter ()
Construct a new undefined handle.
Parameter (Type t, bool is_buffer)
Construct a new parameter of the given type.
Parameter (Type t, bool is_buffer, const std::string &name)
Construct a new parameter of the given type with name given by the third argument.
Type type () const
Get the type of this parameter.
const std::string & name () const
Get the name of this parameter.
bool is_buffer () const
Does this parameter refer to a buffer/image?
template<typename T >
T get_scalar () const
If the parameter is a scalar parameter, get its currently bound value.
Buffer get_buffer () const
If the parameter is a buffer parameter, get its currently bound buffer.
template<typename T >
void set_scalar (T val)
If the parameter is a scalar parameter, set its current value.
void set_buffer (Buffer b)
If the parameter is a buffer parameter, set its current value.
const void * get_scalar_address () const
Get the pointer to the current value of the scalar parameter.
bool defined () const
Tests if this handle is non-NULL.
void set_min_constraint (int dim, Expr e)
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
void set_extent_constraint (int dim, Expr e)
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
void set_stride_constraint (int dim, Expr e)
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Expr min_constraint (int dim)
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Expr extent_constraint (int dim)
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Expr stride_constraint (int dim)
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Detailed Description
A reference-counted handle to a parameter to a halide pipeline.
May be a scalar parameter or a buffer
Definition at line 39 of file Parameter.h.
Constructor & Destructor Documentation
Halide::Internal::Parameter::Parameter () inline
Construct a new undefined handle.
Definition at line 43 of file Parameter.h.
Halide::Internal::Parameter::Parameter (Type t, bool is_buffer) inline
Construct a new parameter of the given type.
If the second argument is true, this is a buffer parameter, otherwise, it is a scalar parameter. The parameter will be given a unique auto-generated name.
Definition at line 49 of file Parameter.h.
Halide::Internal::Parameter::Parameter (Type t, bool is_buffer, const std::string & name) inline
Construct a new parameter of the given type with name given by the third argument.
If the second argument is true, this is a buffer parameter, otherwise, it is a scalar parameter. The parameter will be given a unique auto-generated name.
Definition at line 57 of file Parameter.h.
Member Function Documentation
Type Halide::Internal::Parameter::type () const inline
Get the type of this parameter.
Definition at line 62 of file Parameter.h.
Referenced by Halide::Internal::Call::make(), and Halide::ImageParam::type().
const std::string& Halide::Internal::Parameter::name () const inline
Get the name of this parameter.
Definition at line 68 of file Parameter.h.
Referenced by Halide::Internal::Call::make(), Halide::Param< T >::name(), and Halide::ImageParam::name().
bool Halide::Internal::Parameter::is_buffer () const inline
Does this parameter refer to a buffer/image?
Definition at line 74 of file Parameter.h.
Referenced by extent_constraint(), min_constraint(), set_extent_constraint(), set_min_constraint(), set_stride_constraint(), and stride_constraint().
template<typename T > T Halide::Internal::Parameter::get_scalar () const inline
If the parameter is a scalar parameter, get its currently bound value.
Only relevant when jitting
Definition at line 82 of file Parameter.h.
Referenced by Halide::Param< T >::get().
Buffer Halide::Internal::Parameter::get_buffer () const inline
If the parameter is a buffer parameter, get its currently bound buffer.
Only relevant when jitting
Definition at line 89 of file Parameter.h.
Referenced by Halide::ImageParam::get().
template<typename T > void Halide::Internal::Parameter::set_scalar (T val) inline
If the parameter is a scalar parameter, set its current value.
Only relevant when jitting
Definition at line 97 of file Parameter.h.
Referenced by Halide::Param< T >::set().
void Halide::Internal::Parameter::set_buffer (Buffer b) inline
If the parameter is a buffer parameter, set its current value.
Only relevant when jitting
Definition at line 104 of file Parameter.h.
References Halide::Buffer::defined(), and Halide::Buffer::type().
Referenced by Halide::ImageParam::set().
const void* Halide::Internal::Parameter::get_scalar_address () const inline
Get the pointer to the current value of the scalar parameter.
For a given parameter, this address will never change. Only relevant when jitting.
Definition at line 113 of file Parameter.h.
bool Halide::Internal::Parameter::defined () const inline
Tests if this handle is non-NULL.
Definition at line 119 of file Parameter.h.
Referenced by Halide::ImageParam::defined(), and Halide::Internal::Call::make().
void Halide::Internal::Parameter::set_min_constraint (int dim, Expr e) inline
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Definition at line 126 of file Parameter.h.
References is_buffer().
Referenced by Halide::ImageParam::set_min().
void Halide::Internal::Parameter::set_extent_constraint (int dim, Expr e) inline
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Definition at line 130 of file Parameter.h.
References is_buffer().
Referenced by Halide::ImageParam::set_extent().
void Halide::Internal::Parameter::set_stride_constraint (int dim, Expr e) inline
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Definition at line 134 of file Parameter.h.
References is_buffer().
Referenced by Halide::ImageParam::set_stride().
Expr Halide::Internal::Parameter::min_constraint (int dim) inline
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Definition at line 138 of file Parameter.h.
References is_buffer().
Expr Halide::Internal::Parameter::extent_constraint (int dim) inline
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Definition at line 142 of file Parameter.h.
References is_buffer().
Expr Halide::Internal::Parameter::stride_constraint (int dim) inline
Get and set constraints for the min, extent, and stride (see ImageParam::set_extent)
Definition at line 146 of file Parameter.h.
References is_buffer().
The documentation for this class was generated from the following file:
Parameter.h