Halide: Halide::Param< T > Class Template Reference
Halide::Param< T > Class Template Reference
A scalar parameter to a halide pipeline.
#include <Param.h>
Public Member Functions
Param ()
Construct a scalar parameter of type T with a unique auto-generated name.
Param (const std::string &n)
Construct a scalar parameter of type T with the given name.
const std::string & name () const
Get the name of this parameter.
T get () const
Get the current value of this parameter.
void set (T val)
Set the current value of this parameter.
Type type () const
Get the halide type of T.
operator Expr () const
You can use this parameter as an expression in a halide function definition.
operator Argument () const
Construct the appropriate argument matching this parameter, for the purpose of generating the right type signature when statically compiling halide pipelines.
Detailed Description
template<typename T>
class Halide::Param< T >
A scalar parameter to a halide pipeline.
If you're jitting, this should be bound to an actual value of type T using the set method before you realize the function uses this. If you're statically compiling, this param should appear in the argument list.
Definition at line 21 of file Param.h.
Constructor & Destructor Documentation
template<typename T > Halide::Param< T >::Param () inline
Construct a scalar parameter of type T with a unique auto-generated name.
Definition at line 27 of file Param.h.
template<typename T > Halide::Param< T >::Param (const std::string & n) inline
Construct a scalar parameter of type T with the given name.
Definition at line 30 of file Param.h.
Member Function Documentation
template<typename T > const std::string& Halide::Param< T >::name () const inline
Get the name of this parameter.
Definition at line 33 of file Param.h.
References Halide::Internal::Parameter::name().
Referenced by Halide::Param< T >::operator Argument(), and Halide::Param< T >::operator Expr().
template<typename T > T Halide::Param< T >::get () const inline
Get the current value of this parameter.
Only meaningful when jitting.
Definition at line 38 of file Param.h.
References Halide::Internal::Parameter::get_scalar().
template<typename T > void Halide::Param< T >::set (T val) inline
Set the current value of this parameter.
Only meaningful when jitting
Definition at line 43 of file Param.h.
References Halide::Internal::Parameter::set_scalar().
template<typename T > Type Halide::Param< T >::type () const inline
Get the halide type of T.
Definition at line 48 of file Param.h.
Referenced by Halide::Param< T >::operator Argument().
template<typename T > Halide::Param< T >::operator Expr () const inline
You can use this parameter as an expression in a halide function definition.
Definition at line 54 of file Param.h.
References Halide::Internal::Variable::make(), and Halide::Param< T >::name().
template<typename T > Halide::Param< T >::operator Argument () const inline
Construct the appropriate argument matching this parameter, for the purpose of generating the right type signature when statically compiling halide pipelines.
Definition at line 61 of file Param.h.
References Halide::Param< T >::name(), and Halide::Param< T >::type().
The documentation for this class was generated from the following file:
Param.h