Halide: Halide::ImageParam Class Reference
Halide::ImageParam Class Reference
An Image parameter to a halide pipeline.
#include <Param.h>
Public Member Functions
ImageParam ()
Construct a NULL image parameter handle.
ImageParam (Type t, int d)
Construct an image parameter of the given type and dimensionality, with an auto-generated unique name.
ImageParam (Type t, int d, const std::string &n)
Construct an image parameter of the given type and dimensionality, with the given name.
const std::string & name () const
Get the name of this ImageParam.
Type type () const
Get the type of the image data this ImageParam refers to.
void set (Buffer b)
Bind a buffer or image to this ImageParam.
Buffer get () const
Get the buffer bound to this ImageParam.
bool defined () const
Is this handle non-NULL.
Expr extent (int x) const
Get an expression representing the extent of this image parameter in the given dimension.
Expr stride (int x) const
Get an expression representing the stride of this image in the given dimension.
ImageParam & set_extent (int dim, Expr extent)
Set the extent in a given dimension to equal the given expression.
ImageParam & set_min (int dim, Expr min)
Set the min in a given dimension to equal the given expression.
ImageParam & set_stride (int dim, Expr stride)
Set the stride in a given dimension to equal the given value.
ImageParam & set_bounds (int dim, Expr min, Expr extent)
Set the min and extent in one call.
int dimensions () const
Get the dimensionality of this image parameter.
Expr width () const
Get an expression giving the extent in dimension 0, which by convention is the width of the image.
Expr height () const
Get an expression giving the extent in dimension 1, which by convention is the height of the image.
Expr channels () const
Get an expression giving the extent in dimension 2, which by convention is the channel-count of the image.
operator Argument () const
Construct the appropriate argument matching this parameter, for the purpose of generating the right type signature when statically compiling halide pipelines.
operator Expr () const
Treating the image parameter as an Expr is equivalent to call it with no arguments.
Expr operator() () const
Construct an expression which loads from this image parameter.
Expr operator() (Expr x) const
Construct an expression which loads from this image parameter.
Expr operator() (Expr x, Expr y) const
Construct an expression which loads from this image parameter.
Expr operator() (Expr x, Expr y, Expr z) const
Construct an expression which loads from this image parameter.
Expr operator() (Expr x, Expr y, Expr z, Expr w) const
Construct an expression which loads from this image parameter.
Detailed Description
An Image parameter to a halide pipeline.
E.g., the input image.
Definition at line 67 of file Param.h.
Constructor & Destructor Documentation
Halide::ImageParam::ImageParam () inline
Construct a NULL image parameter handle.
Definition at line 78 of file Param.h.
Halide::ImageParam::ImageParam (Type t, int d) inline
Construct an image parameter of the given type and dimensionality, with an auto-generated unique name.
Definition at line 82 of file Param.h.
Halide::ImageParam::ImageParam (Type t, int d, const std::string & n) inline
Construct an image parameter of the given type and dimensionality, with the given name.
Definition at line 86 of file Param.h.
Member Function Documentation
const std::string& Halide::ImageParam::name () const inline
Get the name of this ImageParam.
Definition at line 89 of file Param.h.
References Halide::Internal::Parameter::name().
Referenced by extent(), operator Argument(), and stride().
Type Halide::ImageParam::type () const inline
Get the type of the image data this ImageParam refers to.
Definition at line 94 of file Param.h.
References Halide::Internal::Parameter::type().
Referenced by operator Argument(), and set().
void Halide::ImageParam::set (Buffer b) inline
Bind a buffer or image to this ImageParam.
Only relevant for jitting
Definition at line 99 of file Param.h.
References Halide::Internal::Parameter::set_buffer(), and type().
Buffer Halide::ImageParam::get () const inline
Get the buffer bound to this ImageParam.
Only relevant for jitting
Definition at line 105 of file Param.h.
References Halide::Internal::Parameter::get_buffer().
bool Halide::ImageParam::defined () const inline
Is this handle non-NULL.
Definition at line 110 of file Param.h.
References Halide::Internal::Parameter::defined().
Expr Halide::ImageParam::extent (int x) const inline
Get an expression representing the extent of this image parameter in the given dimension.
Definition at line 116 of file Param.h.
References Halide::Int(), Halide::Internal::Variable::make(), and name().
Referenced by channels(), height(), and width().
Expr Halide::ImageParam::stride (int x) const inline
Get an expression representing the stride of this image in the given dimension.
Definition at line 124 of file Param.h.
References Halide::Int(), Halide::Internal::Variable::make(), and name().
ImageParam& Halide::ImageParam::set_extent (int dim, Expr extent) inline
Set the extent in a given dimension to equal the given expression.
Images passed in that fail this check will generate a runtime error. Returns a reference to the ImageParam so that these calls may be chained.
This may help the compiler generate better code. E.g:
im.set_extent(0, 100);
tells the compiler that dimension zero must be of extent 100, which may result in simplification of boundary checks. The value can be an arbitrary expression:
im.set_extent(0, im.extent(1));
declares that im is a square image (of unknown size), whereas:
im.set_extent(0, (im.extent(0)/32)*32);
tells the compiler that the extent is a multiple of 32.
Definition at line 151 of file Param.h.
References Halide::Internal::Parameter::set_extent_constraint().
Referenced by set_bounds().
ImageParam& Halide::ImageParam::set_min (int dim, Expr min) inline
Set the min in a given dimension to equal the given expression.
Setting the mins to zero may simplify some addressing math.
Definition at line 159 of file Param.h.
References Halide::Internal::Parameter::set_min_constraint().
Referenced by set_bounds().
ImageParam& Halide::ImageParam::set_stride (int dim, Expr stride) inline
Set the stride in a given dimension to equal the given value.
This is particularly helpful to set when vectorizing. Known strides for the vectorized dimension generate better code.
Definition at line 168 of file Param.h.
References Halide::Internal::Parameter::set_stride_constraint().
ImageParam& Halide::ImageParam::set_bounds (int dim, Expr min, Expr extent) inline
Set the min and extent in one call.
Definition at line 174 of file Param.h.
References set_extent(), and set_min().
int Halide::ImageParam::dimensions () const inline
Get the dimensionality of this image parameter.
Definition at line 179 of file Param.h.
Referenced by operator()().
Expr Halide::ImageParam::width () const inline
Get an expression giving the extent in dimension 0, which by convention is the width of the image.
Definition at line 185 of file Param.h.
References extent().
Expr Halide::ImageParam::height () const inline
Get an expression giving the extent in dimension 1, which by convention is the height of the image.
Definition at line 192 of file Param.h.
References extent().
Expr Halide::ImageParam::channels () const inline
Get an expression giving the extent in dimension 2, which by convention is the channel-count of the image.
Definition at line 199 of file Param.h.
References extent().
Expr Halide::ImageParam::operator() () const inline
Construct an expression which loads from this image parameter.
The location is extended with enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 210 of file Param.h.
References dimensions(), Halide::Var::implicit(), and Halide::Internal::Call::make().
Expr Halide::ImageParam::operator() (Expr x) const inline
Construct an expression which loads from this image parameter.
The location is extended with enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 219 of file Param.h.
References dimensions(), Halide::Var::implicit(), and Halide::Internal::Call::make().
Expr Halide::ImageParam::operator() (Expr x, Expr y) const inline
Construct an expression which loads from this image parameter.
The location is extended with enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 229 of file Param.h.
References dimensions(), Halide::Var::implicit(), and Halide::Internal::Call::make().
Expr Halide::ImageParam::operator() (Expr x, Expr y, Expr z) const inline
Construct an expression which loads from this image parameter.
The location is extended with enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 240 of file Param.h.
References dimensions(), Halide::Var::implicit(), and Halide::Internal::Call::make().
Expr Halide::ImageParam::operator() (Expr x, Expr y, Expr z, Expr w) const inline
Construct an expression which loads from this image parameter.
The location is extended with enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 252 of file Param.h.
References dimensions(), Halide::Var::implicit(), and Halide::Internal::Call::make().
Halide::ImageParam::operator Argument () const inline
Construct the appropriate argument matching this parameter, for the purpose of generating the right type signature when statically compiling halide pipelines.
Definition at line 269 of file Param.h.
References name(), and type().
Halide::ImageParam::operator Expr () const inline
Treating the image parameter as an Expr is equivalent to call it with no arguments.
For example, you can say:
ImageParam im(UInt(8), 2);
Func f;
f = im*2;
This will define f as a two-dimensional function with value at position (x, y) equal to twice the value of the image parameter at the same location.
Definition at line 286 of file Param.h.
The documentation for this class was generated from the following file:
Param.h