Halide: Halide::Internal::Function Class Reference
Halide::Internal::Function Class Reference
A reference-counted handle to Halide's internal representation of a function.
#include <Function.h>
Public Member Functions
Function ()
Construct a new function with no definitions and no name.
void define (const std::vector< std::string > &args, Expr value)
Add a pure definition to this function.
void define_reduction (const std::vector< Expr > &args, Expr value)
Add a reduction definition to this function.
Function (const std::string &n)
Construct a new function with the given name.
const std::string & name () const
Get the name of the function.
const std::vector< std::string > & args () const
Get the pure arguments.
Expr value () const
Get the right-hand-side of the pure definition.
Schedule & schedule ()
Get a handle to the schedule for the purpose of modifying it.
const Schedule & schedule () const
Get a const handle to the schedule for inspecting it.
Schedule & reduction_schedule ()
Get a mutable handle to the schedule for the reduction stage.
const Schedule & reduction_schedule () const
Get a const handle to the schedule for the reduction stage.
Expr reduction_value () const
Get the right-hand-side of the reduction definition.
const std::vector< Expr > & reduction_args () const
Get the left-hand-side of the reduction definition.
ReductionDomain reduction_domain () const
Get the reduction domain for the reduction definition.
bool is_reduction () const
Is this function a reduction?
bool same_as (const Function &other) const
Equality of identity.
const std::string & debug_file () const
Get a const handle to the debug filename.
std::string & debug_file ()
Get a handle to the debug filename.
Detailed Description
A reference-counted handle to Halide's internal representation of a function.
Similar to a front-end Func object, but with no syntactic sugar to help with definitions.
Definition at line 35 of file Function.h.
Constructor & Destructor Documentation
Halide::Internal::Function::Function () inline
Construct a new function with no definitions and no name.
This constructor only exists so that you can make vectors of functions, etc.
Definition at line 43 of file Function.h.
Halide::Internal::Function::Function (const std::string & n) inline
Construct a new function with the given name.
Definition at line 62 of file Function.h.
Member Function Documentation
void Halide::Internal::Function::define (const std::vector< std::string > & args, Expr value)
Add a pure definition to this function.
It may not already have a definition. All the free variables in 'value' must appear in the args list. 'value' must not depend on any reduction domain
void Halide::Internal::Function::define_reduction (const std::vector< Expr > & args, Expr value)
Add a reduction definition to this function.
It must already have a pure definition but not a reduction definition, and the length of args must match the length of args used in the pure definition. 'value' must depend on some reduction domain, and may contain variables from that domain as well as pure variables. Any pure variables must also appear as Variables in the args array, and they must have the same name as the pure definition's argument in the same index.
const std::string& Halide::Internal::Function::name () const inline
Get the name of the function.
Definition at line 67 of file Function.h.
Referenced by Halide::Internal::Call::make().
const std::vector<std::string>& Halide::Internal::Function::args () const inline
Get the pure arguments.
Definition at line 72 of file Function.h.
Referenced by Halide::Internal::Call::make().
Expr Halide::Internal::Function::value () const inline
Get the right-hand-side of the pure definition.
Definition at line 77 of file Function.h.
Referenced by Halide::Internal::Call::make().
Schedule& Halide::Internal::Function::schedule () inline
Get a handle to the schedule for the purpose of modifying it.
Definition at line 83 of file Function.h.
const Schedule& Halide::Internal::Function::schedule () const inline
Get a const handle to the schedule for inspecting it.
Definition at line 88 of file Function.h.
Schedule& Halide::Internal::Function::reduction_schedule () inline
Get a mutable handle to the schedule for the reduction stage.
Definition at line 94 of file Function.h.
const Schedule& Halide::Internal::Function::reduction_schedule () const inline
Get a const handle to the schedule for the reduction stage.
Definition at line 99 of file Function.h.
Expr Halide::Internal::Function::reduction_value () const inline
Get the right-hand-side of the reduction definition.
Definition at line 104 of file Function.h.
Referenced by is_reduction().
const std::vector<Expr>& Halide::Internal::Function::reduction_args () const inline
Get the left-hand-side of the reduction definition.
Definition at line 109 of file Function.h.
ReductionDomain Halide::Internal::Function::reduction_domain () const inline
Get the reduction domain for the reduction definition.
Definition at line 114 of file Function.h.
bool Halide::Internal::Function::is_reduction () const inline
Is this function a reduction?
Definition at line 119 of file Function.h.
References Halide::Internal::IntrusivePtr< T >::defined(), and reduction_value().
bool Halide::Internal::Function::same_as (const Function & other) const inline
Equality of identity.
Definition at line 124 of file Function.h.
const std::string& Halide::Internal::Function::debug_file () const inline
Get a const handle to the debug filename.
Definition at line 129 of file Function.h.
std::string& Halide::Internal::Function::debug_file () inline
Get a handle to the debug filename.
Definition at line 134 of file Function.h.
The documentation for this class was generated from the following file:
Function.h