Halide: Halide::Internal Namespace Reference
Halide::Internal Namespace Reference
Namespaces
namespace IntegerDivision
Classes
struct Interval
struct BufferContents
class CodeGen
A code generator abstract base class.
class CodeGen_ARM
A code generator that emits ARM code from a given Halide stmt.
class CodeGen_C
This class emits C++ code equivalent to a halide Stmt.
class Closure
A helper class to manage closures.
class CodeGen_Posix
A code generator that emits posix code from a given Halide stmt.
class CodeGen_PTX_Dev
A code generator that emits GPU code from a given Halide stmt.
class CodeGen_PTX_Host
A code generator that emits GPU code from a given Halide stmt.
class CodeGen_X86
A code generator that emits x86 code from a given Halide stmt.
struct FunctionContents
class Function
A reference-counted handle to Halide's internal representation of a function.
class RefCount
A class representing a reference count to be used with IntrusivePtr.
struct IntrusivePtr
Intrusive shared pointers have a reference count (a RefCount object) stored in the class itself.
struct IRNodeType
A class representing a type of IR node (e.g.
struct IRNode
The abstract base classes for a node in the Halide IR.
struct BaseStmtNode
IR nodes are split into expressions and statements.
struct BaseExprNode
A base class for expression nodes.
struct ExprNode
We use the "curiously recurring template pattern" to avoid duplicated code in the IR Nodes.
struct StmtNode
struct IRHandle
IR nodes are passed around opaque handles to them.
struct Stmt
A reference-counted handle to a statement node.
struct IntImm
The actual IR nodes begin here.
struct FloatImm
Floating point constants.
struct Cast
Cast a node from one type to another.
struct Add
The sum of two expressions.
struct Sub
The difference of two expressions.
struct Mul
The product of two expressions.
struct Div
The ratio of two expressions.
struct Mod
The remainder of a / b.
struct Min
The lesser of two values.
struct Max
The greater of two values.
struct EQ
Is the first expression equal to the second.
struct NE
Is the first expression not equal to the second.
struct LT
Is the first expression less than the second.
struct LE
Is the first expression less than or equal to the second.
struct GT
Is the first expression greater than the second.
struct GE
Is the first expression greater than or equal to the second.
struct And
Logical and - are both expressions true.
struct Or
Logical or - is at least one of the expression true.
struct Not
Logical not - true if the expression false.
struct Select
A ternary operator.
struct Load
Load a value from a named buffer.
struct Ramp
A linear ramp vector node.
struct Broadcast
A vector with 'width' elements, in which every element is 'value'.
struct Let
A let expression, like you might find in a functional language.
struct LetStmt
The statement form of a let node.
struct PrintStmt
Used largely for debugging and tracing.
struct AssertStmt
If the 'condition' is false, then bail out printing the 'message' to stderr.
struct Pipeline
This node is a helpful annotation to do with permissions.
struct For
A for loop.
struct Store
Store a 'value' to the buffer called 'name' at a given 'index'.
struct Provide
This defines the value of a function at a multi-dimensional location.
struct Allocate
Allocate a scratch area called with the given name, type, and size.
struct Free
Free the resources associated with the given buffer.
struct Range
A single-dimensional span.
struct Realize
Allocate a multi-dimensional buffer of the given type and size.
struct Block
A sequence of statements to be executed in-order.
struct Call
A function call.
struct Variable
A named variable.
class IRMutator
A base class for passes over the IR which modify it (e.g.
class IRPrinter
An IRVisitor that emits IR to the given output stream in a human readable form.
class IRVisitor
A base class for algorithms that need to recursively walk over the IR.
struct JITCompiledModule
Function pointers into a compiled halide module.
struct log
For optional debugging during codegen, use the log class as follows:
struct ModulusRemainder
The result of modulus_remainder analysis.
struct ParameterContents
class Parameter
A reference-counted handle to a parameter to a halide pipeline.
struct ReductionVariable
A single named dimension of a reduction domain.
struct ReductionDomainContents
class ReductionDomain
A reference-counted handle on a reduction domain, which is just a vector of ReductionVariable.
struct Schedule
A schedule for a halide function, which defines where, when, and how it should be evaluated.
class Scope
A common pattern when traversing Halide IR is that you need to keep track of stuff when you find a Let or a LetStmt, and that it should hide previous values with the same name until you leave the Let or LetStmt nodes This class helps with that.
class StmtCompiler
Typedefs
typedef std::vector< Range > Region
A multi-dimensional box.
Enumerations
enum CodeGen_ARM_Options { ARM_Android = 1, ARM_NaCl = 2 }
Bitmask flags for specifying code generation options to CodeGen_ARM.
enum CodeGen_X86_Options { X86_64Bit = 1, X86_SSE41 = 2, X86_AVX = 4, X86_NaCl = 8 }
Bitmask flags for specifying code generation options to CodeGen_X86.
Functions
Interval bounds_of_expr_in_scope (Expr expr, const Scope< Interval > &scope)
Given an expression in some variables, and a map from those variables to their bounds (in the form of (minimum possible value, maximum possible value)), compute two expressions that give the minimum possible value and the maximum possible value of this expression.
Interval bounds_of_expr (Expr expr)
Call bounds_of_expr_in_scope with an empty scope.
std::map< std::string, Region > regions_called (Stmt s)
Compute rectangular domains large enough to cover all the 'Call's to each function that occurs within a given statement.
std::map< std::string, Region > regions_provided (Stmt s)
Compute rectangular domains large enough to cover all the 'Provide's to each function that occur within a given statement.
std::map< std::string, Region > regions_touched (Stmt s)
Compute rectangular domains large enough to cover all Calls and Provides to each function that occurs within a given statement.
Region region_touched (Stmt s, const std::string &func)
Compute a rectangular domain large enough to cover all Calls and Provides to a given function.
Region region_provided (Stmt s, const std::string &func)
Compute a rectangular domain large enough to cover all Provides to a given function.
Region region_called (Stmt s, const std::string &func)
Compute a rectangular domain large enough to cover all Calls to a given function.
Region region_union (const Region &, const Region &)
Compute the smallest bounding box that contains two regions.
void bounds_test ()
Stmt bounds_inference (Stmt, const std::vector< std::string > &realization_order, const std::map< std::string, Function > &environment)
Take a partially lowered statement that includes symbolic representations of the bounds over which things should be realized, and inject expressions defining those bounds.
template<>
RefCount & ref_count< BufferContents > (const BufferContents *p)
template<>
void destroy< BufferContents > (const BufferContents *p)
llvm::Type * llvm_type_of (llvm::LLVMContext *context, Halide::Type t)
Get the llvm type equivalent to a given halide type.
Stmt debug_to_file (Stmt s, const std::map< std::string, Function > &env)
Takes a statement with Realize nodes still unlowered.
Expr extract_odd_lanes (Expr a)
Extract the odd-numbered lanes in a vector.
Expr extract_even_lanes (Expr a)
Extract the even-numbered lanes in a vector.
Expr extract_lane (Expr vec, int lane)
Extract the nth lane of a vector.
Stmt rewrite_interleavings (Stmt s)
Look through a statement for expressions of the form select(ramp % 2 == 0, a, b) and replace them with calls to an interleave intrinsic.
void deinterleave_vector_test ()
Expr finite_difference (Expr expr, const std::string &var)
Compute the analytic derivative of the expression with respect to the variable.
Stmt inject_early_frees (Stmt s)
Take a statement with allocations and inject markers (of the form of calls to "mark buffer dead") after the last use of each allocation.
bool equal (Expr a, Expr b)
Compare expressions for equality of value.
bool equal (Stmt a, Stmt b)
Compare two statements for equality of value.
bool expr_match (Expr pattern, Expr expr, std::vector< Expr > &result)
Does the first expression have the same structure as the second? Variables in the first expression with the name * are interpreted as wildcards, and their matching equivalent in the second expression is placed in the vector give as the third argument.
void expr_match_test ()
bool EXPORT is_const (Expr e)
Is the expression either an IntImm, a FloatImm, or a Cast of the same, or a Ramp or Broadcast of the same.
bool EXPORT is_const (Expr e, int v)
Is the expression an IntImm, FloatImm of a particular value, or a Cast, or Broadcast of the same.
bool EXPORT is_const_power_of_two (Expr e, int *bits)
Is the expression a constant integer power of two.
bool EXPORT is_positive_const (Expr e)
Is the expression a const (as defined by is_const), and also strictly greater than zero (in all lanes, if a vector expression)
bool EXPORT is_negative_const (Expr e)
Is the expression a const (as defined by is_const), and also strictly less than zero (in all lanes, if a vector expression)
bool EXPORT is_zero (Expr e)
Is the expression a const (as defined by is_const), and also equal to zero (in all lanes, if a vector expression)
bool EXPORT is_one (Expr e)
Is the expression a const (as defined by is_const), and also equal to one (in all lanes, if a vector expression)
bool EXPORT is_two (Expr e)
Is the expression a const (as defined by is_const), and also equal to two (in all lanes, if a vector expression)
int EXPORT int_cast_constant (Type t, int val)
Given an integer value, cast it into a designated integer type and return the bits as int.
Expr EXPORT make_const (Type t, int val)
Construct a const of the given type.
Expr make_bool (bool val, int width=1)
Construct a boolean constant from a C++ boolean value.
Expr EXPORT make_zero (Type t)
Construct the representation of zero in the given type.
Expr EXPORT make_one (Type t)
Construct the representation of one in the given type.
Expr EXPORT make_two (Type t)
Construct the representation of two in the given type.
Expr EXPORT const_true (int width=1)
Construct the constant boolean true.
Expr EXPORT const_false (int width=1)
Construct the constant boolean false.
void EXPORT match_types (Expr &a, Expr &b)
Coerce the two expressions to have the same type, using C-style casting rules.
std::ostream & operator<< (std::ostream &stream, Stmt)
Emit a halide statement on an output stream (such as std::cout) in a human-readable form.
std::ostream & operator<< (std::ostream &stream, const For::ForType &)
Emit a halide for loop type (vectorized, serial, etc) in a human readable form.
Stmt lower (Function f)
Given a halide function with a schedule, create a statement that evaluates it.
void lower_test ()
ModulusRemainder modulus_remainder (Expr e)
For things like alignment analysis, often it's helpful to know if an integer expression is some multiple of a constant plus some other constant.
ModulusRemainder modulus_remainder (Expr e, const Scope< ModulusRemainder > &scope)
If we have alignment information about external variables, we can let the analysis know about that using this version of modulus_remainder:
bool reduce_expr_modulo (Expr e, int modulus, int *remainder)
Reduce an expression modulo some integer.
void modulus_remainder_test ()
int gcd (int, int)
The greatest common divisor of two integers.
Stmt remove_dead_lets (Stmt s)
Prune LetStmt and Let nodes that define variables that are never used.
Stmt remove_trivial_for_loops (Stmt s)
Convert for loops of size 1 into LetStmt nodes, which allows for further simplification.
template<typename T >
std::ostream & operator<< (std::ostream &stream, Scope< T > &s)
template<typename T >
T mod_imp (T a, T b)
Implementations of division and mod that are specific to Halide.
template<>
float mod_imp< float > (float a, float b)
template<>
double mod_imp< double > (double a, double b)
template<typename T >
T div_imp (T a, T b)
void simplify_test ()
Stmt sliding_window (Stmt s, const std::map< std::string, Function > &env)
Perform sliding window optimizations on a halide statement.
Stmt storage_flattening (Stmt s, const std::map< std::string, Function > &env)
Take a statement with multi-dimensional Realize, Provide, and Call nodes, and turn it into a statement with single-dimensional Allocate, Store, and Load nodes respectively.
Stmt storage_folding (Stmt s)
Fold storage of functions if possible.
Expr substitute (std::string name, Expr replacement, Expr expr)
Substitute variables with the given name with the replacement expression within expr.
Stmt substitute (std::string name, Expr replacement, Stmt stmt)
Substitute variables with the given name with the replacement expression within stmt.
Stmt inject_tracing (Stmt)
Take a statement representing a halide pipeline, and (depending on the environment variable HL_TRACE), inject print statements at interesting points, such as allocations.
int tracing_level ()
Gets the current tracing level (by reading HL_TRACE)
Stmt unroll_loops (Stmt)
Take a statement with for loops marked for unrolling, and convert each into several copies of the innermost statement.
EXPORT std::string unique_name (char prefix)
Generate a unique name starting with the given character.
EXPORT std::string unique_name (const std::string &name)
Generate a unique name starting with the given string.
EXPORT bool starts_with (const std::string &str, const std::string &prefix)
Test if the first string starts with the second string.
EXPORT bool ends_with (const std::string &str, const std::string &suffix)
Test if the first string ends with the second string.
EXPORT std::string base_name (const std::string &name)
Return the final token of the name string, assuming a fully qualified name delimited by '.
Stmt vectorize_loops (Stmt)
Take a statement with for loops marked for vectorization, and turn them into single statements that operate on vectors.
template<typename T >
EXPORT RefCount & ref_count (const T *)
Because in this header we don't yet know how client classes store their RefCount (and we don't want to depend on the declarations of the client classes), any class that you want to hold onto via one of these must provide implementations of ref_count and destroy, which we forward-declare here.
template<typename T >
EXPORT void destroy (const T *)
Because in this header we don't yet know how client classes store their RefCount (and we don't want to depend on the declarations of the client classes), any class that you want to hold onto via one of these must provide implementations of ref_count and destroy, which we forward-declare here.
Stmt simplify (Stmt)
Perform a a wide range of simplifications to expressions and statements, including constant folding, substituting in trivial values, arithmetic rearranging, etc.
Expr simplify (Expr)
Perform a a wide range of simplifications to expressions and statements, including constant folding, substituting in trivial values, arithmetic rearranging, etc.
template<typename T >
std::vector< T > vec (T a)
Build small vectors of up to 6 elements.
template<typename T >
std::vector< T > vec (T a, T b)
Build small vectors of up to 6 elements.
template<typename T >
std::vector< T > vec (T a, T b, T c)
Build small vectors of up to 6 elements.
template<typename T >
std::vector< T > vec (T a, T b, T c, T d)
Build small vectors of up to 6 elements.
template<typename T >
std::vector< T > vec (T a, T b, T c, T d, T e)
Build small vectors of up to 6 elements.
template<typename T >
std::vector< T > vec (T a, T b, T c, T d, T e, T f)
Build small vectors of up to 6 elements.
Typedef Documentation
typedef std::vector<Range> Halide::Internal::Region
A multi-dimensional box.
The outer product of the elements
Definition at line 798 of file IR.h.
Enumeration Type Documentation
enum Halide::Internal::CodeGen_ARM_Options
Bitmask flags for specifying code generation options to CodeGen_ARM.
Enumerator
ARM_Android
ARM_NaCl
Compile targetting the Android standard library.
Definition at line 14 of file CodeGen_ARM.h.
enum Halide::Internal::CodeGen_X86_Options
Bitmask flags for specifying code generation options to CodeGen_X86.
Enumerator
X86_64Bit
X86_SSE41
Compile for x86_64.
X86_AVX
Compile for SSE 4.1.
X86_NaCl
Compile for AVX (v1)
Definition at line 14 of file CodeGen_X86.h.
Function Documentation
Interval Halide::Internal::bounds_of_expr_in_scope (Expr expr, const Scope< Interval > & scope)
Given an expression in some variables, and a map from those variables to their bounds (in the form of (minimum possible value, maximum possible value)), compute two expressions that give the minimum possible value and the maximum possible value of this expression.
Max or min may be undefined expressions if the value is not bounded above or below.
This is for tasks such as deducing the region of a buffer loaded by a chunk of code.
Interval Halide::Internal::bounds_of_expr (Expr expr)
Call bounds_of_expr_in_scope with an empty scope.
std::map<std::string, Region> Halide::Internal::regions_called (Stmt s)
Compute rectangular domains large enough to cover all the 'Call's to each function that occurs within a given statement.
This is useful for figuring out what regions of things to evaluate.
std::map<std::string, Region> Halide::Internal::regions_provided (Stmt s)
Compute rectangular domains large enough to cover all the 'Provide's to each function that occur within a given statement.
This is useful for figuring out what region of a function a scattering reduction (e.g. a histogram) might touch.
std::map<std::string, Region> Halide::Internal::regions_touched (Stmt s)
Compute rectangular domains large enough to cover all Calls and Provides to each function that occurs within a given statement.
Region Halide::Internal::region_touched (Stmt s, const std::string & func)
Compute a rectangular domain large enough to cover all Calls and Provides to a given function.
Region Halide::Internal::region_provided (Stmt s, const std::string & func)
Compute a rectangular domain large enough to cover all Provides to a given function.
Region Halide::Internal::region_called (Stmt s, const std::string & func)
Compute a rectangular domain large enough to cover all Calls to a given function.
Region Halide::Internal::region_union (const Region & , const Region &)
Compute the smallest bounding box that contains two regions.
void Halide::Internal::bounds_test ()
Stmt Halide::Internal::bounds_inference (Stmt , const std::vector< std::string > & realization_order, const std::map< std::string, Function > & environment)
Take a partially lowered statement that includes symbolic representations of the bounds over which things should be realized, and inject expressions defining those bounds.
template<> RefCount& Halide::Internal::ref_count< BufferContents > (const BufferContents * p) inline
Definition at line 285 of file Buffer.h.
template<> void Halide::Internal::destroy< BufferContents > (const BufferContents * p) inline
Definition at line 290 of file Buffer.h.
llvm::Type* Halide::Internal::llvm_type_of (llvm::LLVMContext * context, Halide::Type t)
Get the llvm type equivalent to a given halide type.
Stmt Halide::Internal::debug_to_file (Stmt s, const std::map< std::string, Function > & env)
Takes a statement with Realize nodes still unlowered.
If the corresponding functions have a debug_file set, then inject code that will dump the contents of those functions to a file after the realization.
Expr Halide::Internal::extract_odd_lanes (Expr a)
Extract the odd-numbered lanes in a vector.
Expr Halide::Internal::extract_even_lanes (Expr a)
Extract the even-numbered lanes in a vector.
Expr Halide::Internal::extract_lane (Expr vec, int lane)
Extract the nth lane of a vector.
Stmt Halide::Internal::rewrite_interleavings (Stmt s)
Look through a statement for expressions of the form select(ramp % 2 == 0, a, b) and replace them with calls to an interleave intrinsic.
void Halide::Internal::deinterleave_vector_test ()
Expr Halide::Internal::finite_difference (Expr expr, const std::string & var)
Compute the analytic derivative of the expression with respect to the variable.
May returned an undefined Expr if it's non-differentiable. Compute the finite difference version of the derivative: expr(var+1) - expr(var). The reason to do this as a derivative, instead of just explicitly constructing expr(var+1) - expr(var), is so that we don't have to do so much simplification later. For example, the finite-difference derivative of 2*x is trivially 2, whereas 2*(x+1) - 2*x may or may not simplify down to 2, depending on the quality of our simplification routine.
Most rules for the finite difference and the true derivative are the same. The quotient and product rules are not.
Stmt Halide::Internal::inject_early_frees (Stmt s)
Take a statement with allocations and inject markers (of the form of calls to "mark buffer dead") after the last use of each allocation.
Targets may use this to free buffers earlier than the close of their Allocate node.
template<typename T > EXPORT RefCount& Halide::Internal::ref_count (const T *)
Because in this header we don't yet know how client classes store their RefCount (and we don't want to depend on the declarations of the client classes), any class that you want to hold onto via one of these must provide implementations of ref_count and destroy, which we forward-declare here.
E.g. if you want to use IntrusivePtr<MyClass>, then you should define something like this in MyClass.cpp (assuming MyClass has a field: mutable int ref_count):
template<> RefCount &ref_count<MyClass>(const MyClass *c) {return c->ref_count;} template<> void destroy<MyClass>(const MyClass *c) {delete c;}
Referenced by Halide::Internal::IntrusivePtr< Halide::Internal::ReductionDomainContents >::IntrusivePtr().
template<typename T > EXPORT void Halide::Internal::destroy (const T *)
Because in this header we don't yet know how client classes store their RefCount (and we don't want to depend on the declarations of the client classes), any class that you want to hold onto via one of these must provide implementations of ref_count and destroy, which we forward-declare here.
E.g. if you want to use IntrusivePtr<MyClass>, then you should define something like this in MyClass.cpp (assuming MyClass has a field: mutable int ref_count):
template<> RefCount &ref_count<MyClass>(const MyClass *c) {return c->ref_count;} template<> void destroy<MyClass>(const MyClass *c) {delete c;}
bool Halide::Internal::equal (Expr a, Expr b)
Compare expressions for equality of value.
Traverses entire expression tree. For equality of reference, use Expr::same_as
bool Halide::Internal::equal (Stmt a, Stmt b)
Compare two statements for equality of value.
Traverses entire statement tree. For equality of reference, use Stmt::same_as
bool Halide::Internal::expr_match (Expr pattern, Expr expr, std::vector< Expr > & result)
Does the first expression have the same structure as the second? Variables in the first expression with the name * are interpreted as wildcards, and their matching equivalent in the second expression is placed in the vector give as the third argument.
For example:
Expr x = new Variable(Int(32), "*");
match(x + x, 3 + (2*k), result)
should return true, and set result[0] to 3 and result[1] to 2*k.
void Halide::Internal::expr_match_test ()
bool EXPORT Halide::Internal::is_const (Expr e)
Is the expression either an IntImm, a FloatImm, or a Cast of the same, or a Ramp or Broadcast of the same.
Doesn't do any constant folding.
bool EXPORT Halide::Internal::is_const (Expr e, int v)
Is the expression an IntImm, FloatImm of a particular value, or a Cast, or Broadcast of the same.
bool EXPORT Halide::Internal::is_const_power_of_two (Expr e, int * bits)
Is the expression a constant integer power of two.
Also returns log base two of the expression if it is.
bool EXPORT Halide::Internal::is_positive_const (Expr e)
Is the expression a const (as defined by is_const), and also strictly greater than zero (in all lanes, if a vector expression)
bool EXPORT Halide::Internal::is_negative_const (Expr e)
Is the expression a const (as defined by is_const), and also strictly less than zero (in all lanes, if a vector expression)
bool EXPORT Halide::Internal::is_zero (Expr e)
Is the expression a const (as defined by is_const), and also equal to zero (in all lanes, if a vector expression)
Referenced by Halide::Internal::IntrusivePtr< Halide::Internal::ReductionDomainContents >::IntrusivePtr().
bool EXPORT Halide::Internal::is_one (Expr e)
Is the expression a const (as defined by is_const), and also equal to one (in all lanes, if a vector expression)
bool EXPORT Halide::Internal::is_two (Expr e)
Is the expression a const (as defined by is_const), and also equal to two (in all lanes, if a vector expression)
int EXPORT Halide::Internal::int_cast_constant (Type t, int val)
Given an integer value, cast it into a designated integer type and return the bits as int.
Unsigned types are returned as bits in the int and should be cast to unsigned int for comparison. int_cast_constant implements bit manipulations to wrap val into the value range of the Type t. For example, int_cast_constant(UInt(16), -1) returns 65535 int_cast_constant(Int(8), 128) returns -128
Expr EXPORT Halide::Internal::make_const (Type t, int val)
Construct a const of the given type.
Expr Halide::Internal::make_bool (bool val, int width = 1)
Construct a boolean constant from a C++ boolean value.
May also be a vector if width is given. It is not possible to coerce a C++ boolean to Expr because if we provide such a path then char objects can ambiguously be converted to Halide Expr or to std::string. The problem is that C++ does not have a real bool type - it is in fact close enough to char that C++ does not know how to distinguish them. make_bool is the explicit coercion.
Expr EXPORT Halide::Internal::make_zero (Type t)
Construct the representation of zero in the given type.
Referenced by Halide::operator-().
Expr EXPORT Halide::Internal::make_one (Type t)
Construct the representation of one in the given type.
Expr EXPORT Halide::Internal::make_two (Type t)
Construct the representation of two in the given type.
Expr EXPORT Halide::Internal::const_true (int width = 1)
Construct the constant boolean true.
May also be a vector of trues, if a width argument is given.
Expr EXPORT Halide::Internal::const_false (int width = 1)
Construct the constant boolean false.
May also be a vector of falses, if a width argument is given.
void EXPORT Halide::Internal::match_types (Expr & a, Expr & b)
Coerce the two expressions to have the same type, using C-style casting rules.
For the purposes of casting, a boolean type is UInt(1). We use the following procedure:
If the types already match, do nothing.
Then, if one type is a vector and the other is a scalar, the scalar is broadcast to match the vector width, and we continue.
Then, if one type is floating-point and the other is not, the non-float is cast to the floating-point type, and we're done.
Then, if neither is a float but one of the two is a constant, the constant is cast to match the non-const type and we're done. For example, e has type UInt(8), then (e*32) also has type UInt(8), despite the overflow that may occur. Note that this also means that (e*(-1)) is positive, and is equivalent to (e*255) - i.e. the (-1) is cast to a UInt(8) before the multiplication.
Then, if both types are unsigned ints, the one with fewer bits is cast to match the one with more bits and we're done.
Then, if both types are signed ints, the one with fewer bits is cast to match the one with more bits and we're done.
Finally, if one type is an unsigned int and the other type is a signed int, both are cast to a signed int with the greater of the two bit-widths. For example, matching an Int(8) with a UInt(16) results in an Int(16).
Referenced by Halide::max(), Halide::min(), Halide::operator!=(), Halide::operator%(), Halide::operator*(), Halide::operator+(), Halide::operator-(), Halide::operator/(), Halide::operator<(), Halide::operator<=(), Halide::operator==(), Halide::operator>(), and Halide::operator>=().
std::ostream& Halide::Internal::operator<< (std::ostream & stream, Stmt)
Emit a halide statement on an output stream (such as std::cout) in a human-readable form.
std::ostream& Halide::Internal::operator<< (std::ostream & stream, const For::ForType &)
Emit a halide for loop type (vectorized, serial, etc) in a human readable form.
Stmt Halide::Internal::lower (Function f)
Given a halide function with a schedule, create a statement that evaluates it.
Automatically pulls in all the functions f depends on
void Halide::Internal::lower_test ()
ModulusRemainder Halide::Internal::modulus_remainder (Expr e)
For things like alignment analysis, often it's helpful to know if an integer expression is some multiple of a constant plus some other constant.
For example, it is straight-forward to deduce that ((10*x + 2)*(6*y - 3) - 1) is congruent to five modulo six.
We get the most information when the modulus is large. E.g. if something is congruent to 208 modulo 384, then we also know it's congruent to 0 mod 8, and we can possibly use it as an index for an aligned load. If all else fails, we can just say that an integer is congruent to zero modulo one.
ModulusRemainder Halide::Internal::modulus_remainder (Expr e, const Scope< ModulusRemainder > & scope)
If we have alignment information about external variables, we can let the analysis know about that using this version of modulus_remainder:
bool Halide::Internal::reduce_expr_modulo (Expr e, int modulus, int * remainder)
Reduce an expression modulo some integer.
Returns true and assigns to remainder if an answer could be found.
void Halide::Internal::modulus_remainder_test ()
int Halide::Internal::gcd (int , int)
The greatest common divisor of two integers.
Stmt Halide::Internal::remove_dead_lets (Stmt s)
Prune LetStmt and Let nodes that define variables that are never used.
Done as a final pass of lowering.
Stmt Halide::Internal::remove_trivial_for_loops (Stmt s)
Convert for loops of size 1 into LetStmt nodes, which allows for further simplification.
Done during a late stage of lowering.
template<typename T > std::ostream& Halide::Internal::operator<< (std::ostream & stream, Scope< T > & s)
Definition at line 90 of file Scope.h.
Stmt Halide::Internal::simplify (Stmt)
Perform a a wide range of simplifications to expressions and statements, including constant folding, substituting in trivial values, arithmetic rearranging, etc.
Expr Halide::Internal::simplify (Expr)
Perform a a wide range of simplifications to expressions and statements, including constant folding, substituting in trivial values, arithmetic rearranging, etc.
template<typename T > T Halide::Internal::mod_imp (T a, T b) inline
Implementations of division and mod that are specific to Halide.
Use these implementations; do not use native C division or mod to simplify Halide expressions.
Definition at line 27 of file Simplify.h.
References Halide::Type::is_int().
template<> float Halide::Internal::mod_imp< float > (float a, float b) inline
Definition at line 36 of file Simplify.h.
template<> double Halide::Internal::mod_imp< double > (double a, double b) inline
Definition at line 41 of file Simplify.h.
References Halide::floor().
template<typename T > T Halide::Internal::div_imp (T a, T b) inline
Definition at line 48 of file Simplify.h.
References Halide::Type::bits, and Halide::Type::is_int().
void Halide::Internal::simplify_test ()
Stmt Halide::Internal::sliding_window (Stmt s, const std::map< std::string, Function > & env)
Perform sliding window optimizations on a halide statement.
I.e. don't bother computing points in a function that have provably already been computed by a previous iteration.
Stmt Halide::Internal::storage_flattening (Stmt s, const std::map< std::string, Function > & env)
Take a statement with multi-dimensional Realize, Provide, and Call nodes, and turn it into a statement with single-dimensional Allocate, Store, and Load nodes respectively.
Stmt Halide::Internal::storage_folding (Stmt s)
Fold storage of functions if possible.
This means reducing one of the dimensions module something for the purpose of storage, if we can prove that this is safe to do. E.g consider:
f(x) = ...
g(x) = f(x-1) + f(x)
f.store_root().compute_at(g, x);
We can store f as a circular buffer of size two, instead of allocating space for all of it.
Expr Halide::Internal::substitute (std::string name, Expr replacement, Expr expr)
Substitute variables with the given name with the replacement expression within expr.
Stmt Halide::Internal::substitute (std::string name, Expr replacement, Stmt stmt)
Substitute variables with the given name with the replacement expression within stmt.
Stmt Halide::Internal::inject_tracing (Stmt)
Take a statement representing a halide pipeline, and (depending on the environment variable HL_TRACE), inject print statements at interesting points, such as allocations.
Should be done before storage flattening, but after all bounds inference.
int Halide::Internal::tracing_level ()
Gets the current tracing level (by reading HL_TRACE)
Stmt Halide::Internal::unroll_loops (Stmt)
Take a statement with for loops marked for unrolling, and convert each into several copies of the innermost statement.
I.e. unroll the loop.
template<typename T > std::vector<T> Halide::Internal::vec (T a)
Build small vectors of up to 6 elements.
If we used C++11 and had vector initializers, this would not be necessary, but we don't want to rely on C++11 support.
Definition at line 38 of file Util.h.
Referenced by Halide::abs(), Halide::acos(), Halide::acosh(), Halide::asin(), Halide::asinh(), Halide::atan(), Halide::atanh(), Halide::ceil(), Halide::cos(), Halide::cosh(), Halide::exp(), Halide::floor(), Halide::hypot(), Halide::log(), Halide::pow(), Halide::round(), Halide::sin(), Halide::sinh(), Halide::sqrt(), Halide::tan(), and Halide::tanh().
template<typename T > std::vector<T> Halide::Internal::vec (T a, T b)
Build small vectors of up to 6 elements.
If we used C++11 and had vector initializers, this would not be necessary, but we don't want to rely on C++11 support.
Definition at line 45 of file Util.h.
template<typename T > std::vector<T> Halide::Internal::vec (T a, T b, T c)
Build small vectors of up to 6 elements.
If we used C++11 and had vector initializers, this would not be necessary, but we don't want to rely on C++11 support.
Definition at line 53 of file Util.h.
template<typename T > std::vector<T> Halide::Internal::vec (T a, T b, T c, T d)
Build small vectors of up to 6 elements.
If we used C++11 and had vector initializers, this would not be necessary, but we don't want to rely on C++11 support.
Definition at line 62 of file Util.h.
template<typename T > std::vector<T> Halide::Internal::vec (T a, T b, T c, T d, T e)
Build small vectors of up to 6 elements.
If we used C++11 and had vector initializers, this would not be necessary, but we don't want to rely on C++11 support.
Definition at line 72 of file Util.h.
template<typename T > std::vector<T> Halide::Internal::vec (T a, T b, T c, T d, T e, T f)
Build small vectors of up to 6 elements.
If we used C++11 and had vector initializers, this would not be necessary, but we don't want to rely on C++11 support.
Definition at line 83 of file Util.h.
EXPORT std::string Halide::Internal::unique_name (char prefix)
Generate a unique name starting with the given character.
It's unique relative to all other calls to unique_name done by this process. Not thread-safe.
Referenced by Halide::lambda().
EXPORT std::string Halide::Internal::unique_name (const std::string & name)
Generate a unique name starting with the given string.
Not thread-safe.
EXPORT bool Halide::Internal::starts_with (const std::string & str, const std::string & prefix)
Test if the first string starts with the second string.
Referenced by Halide::Internal::Schedule::LoopLevel::match().
EXPORT bool Halide::Internal::ends_with (const std::string & str, const std::string & suffix)
Test if the first string ends with the second string.
Referenced by Halide::Internal::Schedule::LoopLevel::match().
EXPORT std::string Halide::Internal::base_name (const std::string & name)
Return the final token of the name string, assuming a fully qualified name delimited by '.
'
Stmt Halide::Internal::vectorize_loops (Stmt)
Take a statement with for loops marked for vectorization, and turn them into single statements that operate on vectors.
The loops in question must have constant extent.