Halide: Halide Namespace Reference
Halide Namespace Reference
Namespaces
namespace Internal
Classes
struct Argument
A struct representing an argument to a halide-generated function.
class Buffer
The internal representation of an image, or other dense array data.
class FuncRefVar
A fragment of front-end syntax of the form f(x, y, z), where x, y, z are Vars.
class FuncRefExpr
A fragment of front-end syntax of the form f(x, y, z), where x, y, z are Exprs.
class ScheduleHandle
A wrapper around a schedule used for common schedule manipulations.
class Func
A halide function.
class Image
A reference-counted handle on a dense multidimensional array containing scalar values of type T.
struct Expr
A fragment of Halide syntax.
class Param
A scalar parameter to a halide pipeline.
class ImageParam
An Image parameter to a halide pipeline.
class RVar
A reduction variable represents a single dimension of a reduction domain (RDom).
class RDom
A multi-dimensional domain over which to iterate.
struct Type
Types in the halide type system.
class Var
A Halide variable, to be used when defining functions.
Functions
template<typename T >
Expr cast (Expr a)
Cast an expression to the halide type corresponding to the C++ type T.
Expr cast (Type t, Expr a)
Cast an expression to a new type.
Expr operator+ (Expr a, Expr b)
Return the sum of two expressions, doing any necessary type coercion using Internal::match_types.
Expr & operator+= (Expr &a, Expr b)
Modify the first expression to be the sum of two expressions, without changing its type.
Expr operator- (Expr a, Expr b)
Return the difference of two expressions, doing any necessary type coercion using Internal::match_types.
Expr operator- (Expr a)
Return the negative of the argument.
Expr & operator-= (Expr &a, Expr b)
Modify the first expression to be the difference of two expressions, without changing its type.
Expr operator* (Expr a, Expr b)
Return the product of two expressions, doing any necessary type coercion using Internal::match_types.
Expr & operator*= (Expr &a, Expr b)
Modify the first expression to be the product of two expressions, without changing its type.
Expr operator/ (Expr a, Expr b)
Return the ratio of two expressions, doing any necessary type coercion using Internal::match_types.
Expr & operator/= (Expr &a, Expr b)
Modify the first expression to be the ratio of two expressions, without changing its type.
Expr operator% (Expr a, Expr b)
Return the first argument reduced modulo the second, doing any necessary type coercion using Internal::match_types.
Expr operator> (Expr a, Expr b)
Return a boolean expression that tests whether the first argument is greater than the second, after doing any necessary type coercion using Internal::match_types.
Expr operator< (Expr a, Expr b)
Return a boolean expression that tests whether the first argument is less than the second, after doing any necessary type coercion using Internal::match_types.
Expr operator<= (Expr a, Expr b)
Return a boolean expression that tests whether the first argument is less than or equal to the second, after doing any necessary type coercion using Internal::match_types.
Expr operator>= (Expr a, Expr b)
Return a boolean expression that tests whether the first argument is greater than or equal to the second, after doing any necessary type coercion using Internal::match_types.
Expr operator== (Expr a, Expr b)
Return a boolean expression that tests whether the first argument is equal to the second, after doing any necessary type coercion using Internal::match_types.
Expr operator!= (Expr a, Expr b)
Return a boolean expression that tests whether the first argument is not equal to the second, after doing any necessary type coercion using Internal::match_types.
Expr operator&& (Expr a, Expr b)
Returns the logical and of the two arguments.
Expr operator|| (Expr a, Expr b)
Returns the logical or of the two arguments.
Expr operator! (Expr a)
Returns the logical not the argument.
Expr max (Expr a, Expr b)
Returns an expression representing the greater of the two arguments, after doing any necessary type coercion using Internal::match_types.
Expr min (Expr a, Expr b)
Returns an expression representing the lesser of the two arguments, after doing any necessary type coercion using Internal::match_types.
Expr clamp (Expr a, Expr min_val, Expr max_val)
Clamps an expression to lie within the given bounds.
Expr abs (Expr a)
Returns the absolute value of a signed integer or floating-point expression.
Expr select (Expr a, Expr b, Expr c)
Returns an expression equivalent to the ternary operator in C.
Expr sin (Expr x)
Return the sine of a floating-point expression.
Expr asin (Expr x)
Return the arcsine of a floating-point expression.
Expr cos (Expr x)
Return the cosine of a floating-point expression.
Expr acos (Expr x)
Return the arccosine of a floating-point expression.
Expr tan (Expr x)
Return the tangent of a floating-point expression.
Expr atan (Expr x)
Return the arctangent of a floating-point expression.
Expr sinh (Expr x)
Return the hyperbolic sine of a floating-point expression.
Expr asinh (Expr x)
Return the hyperbolic arcsinhe of a floating-point expression.
Expr cosh (Expr x)
Return the hyperbolic cosine of a floating-point expression.
Expr acosh (Expr x)
Return the hyperbolic arccosine of a floating-point expression.
Expr tanh (Expr x)
Return the hyperbolic tangent of a floating-point expression.
Expr atanh (Expr x)
Return the hyperbolic arctangent of a floating-point expression.
Expr sqrt (Expr x)
Return the square root of a floating-point expression.
Expr hypot (Expr x, Expr y)
Return the square root of a floating-point expression.
Expr exp (Expr x)
Return the exponential of a floating-point expression.
Expr log (Expr x)
Return the logarithm of a floating-point expression.
Expr floor (Expr x)
Return the greatest whole number less than or equal to a floating-point expression.
Expr ceil (Expr x)
Return the least whole number greater than or equal to a floating-point expression.
Expr round (Expr x)
Return the whole number closest to a floating-point expression.
Expr pow (Expr x, Expr y)
Return one floating point expression raised to the power of another.
std::ostream & operator<< (std::ostream &stream, Expr)
Emit an expression on an output stream (such as std::cout) in a human-readable form.
std::ostream & operator<< (std::ostream &stream, Type)
Emit a halide type on an output stream (such as std::cout) in a human-readable form.
Func lambda (Expr e)
Create a zero-dimensional halide function that returns the given expression.
Func lambda (Var x, Expr e)
Create a 1-D halide function in the first argument that returns the second argument.
Func lambda (Var x, Var y, Expr e)
Create a 2-D halide function in the first two arguments that returns the last argument.
Func lambda (Var x, Var y, Var z, Expr e)
Create a 3-D halide function in the first three arguments that returns the last argument.
Func lambda (Var x, Var y, Var z, Var w, Expr e)
Create a 4-D halide function in the first four arguments that returns the last argument.
std::ostream & operator<< (std::ostream &stream, RVar)
Emit an RVar in a human-readable form.
std::ostream & operator<< (std::ostream &stream, RDom)
Emit an RDom in a human-readable form.
Type Int (int bits, int width=1)
Constructing a signed integer type.
Type UInt (int bits, int width=1)
Constructing an unsigned integer type.
Type Float (int bits, int width=1)
Construct a floating-point type.
Type Bool (int width=1)
Construct a boolean type.
template<typename T >
Type type_of ()
Construct the halide equivalent of a C type.
template<>
Type type_of< float > ()
template<>
Type type_of< double > ()
template<>
Type type_of< unsigned char > ()
template<>
Type type_of< unsigned short > ()
template<>
Type type_of< unsigned int > ()
template<>
Type type_of< bool > ()
template<>
Type type_of< char > ()
template<>
Type type_of< short > ()
template<>
Type type_of< int > ()
template<>
Type type_of< signed char > ()
EXPORT Expr sum (Expr)
An inline reduction.
EXPORT Expr product (Expr)
An inline reduction.
EXPORT Expr maximum (Expr)
An inline reduction.
EXPORT Expr minimum (Expr)
An inline reduction.
Function Documentation
EXPORT Expr Halide::sum (Expr)
An inline reduction.
This is suitable for convolution-type operations - the reduction will be computed in the innermost loop that it is used in. The argument may contain free or implicit variables, and must refer to some reduction domain. The free variables are still free in the return value, but the reduction domain is captured - the result expression does not refer to a reduction domain and can be used in a pure function definition.
An example:
Func f, g;
Var x;
RDom r(0, 10);
f(x) = x*x;
g(x) = sum(f(x + r));
Here g computes some blur of x, but g is still a pure function. The sum is being computed by an anonymous reduction function that is scheduled innermost within g.
EXPORT Expr Halide::product (Expr)
An inline reduction.
This is suitable for convolution-type operations - the reduction will be computed in the innermost loop that it is used in. The argument may contain free or implicit variables, and must refer to some reduction domain. The free variables are still free in the return value, but the reduction domain is captured - the result expression does not refer to a reduction domain and can be used in a pure function definition.
An example:
Func f, g;
Var x;
RDom r(0, 10);
f(x) = x*x;
g(x) = sum(f(x + r));
Here g computes some blur of x, but g is still a pure function. The sum is being computed by an anonymous reduction function that is scheduled innermost within g.
EXPORT Expr Halide::maximum (Expr)
An inline reduction.
This is suitable for convolution-type operations - the reduction will be computed in the innermost loop that it is used in. The argument may contain free or implicit variables, and must refer to some reduction domain. The free variables are still free in the return value, but the reduction domain is captured - the result expression does not refer to a reduction domain and can be used in a pure function definition.
An example:
Func f, g;
Var x;
RDom r(0, 10);
f(x) = x*x;
g(x) = sum(f(x + r));
Here g computes some blur of x, but g is still a pure function. The sum is being computed by an anonymous reduction function that is scheduled innermost within g.
EXPORT Expr Halide::minimum (Expr)
An inline reduction.
This is suitable for convolution-type operations - the reduction will be computed in the innermost loop that it is used in. The argument may contain free or implicit variables, and must refer to some reduction domain. The free variables are still free in the return value, but the reduction domain is captured - the result expression does not refer to a reduction domain and can be used in a pure function definition.
An example:
Func f, g;
Var x;
RDom r(0, 10);
f(x) = x*x;
g(x) = sum(f(x + r));
Here g computes some blur of x, but g is still a pure function. The sum is being computed by an anonymous reduction function that is scheduled innermost within g.
template<typename T > Expr Halide::cast (Expr a) inline
Cast an expression to the halide type corresponding to the C++ type T.
Definition at line 124 of file IROperator.h.
Referenced by cast(), clamp(), operator*=(), operator+=(), operator-=(), and operator/=().
Expr Halide::cast (Type t, Expr a) inline
Cast an expression to a new type.
Definition at line 129 of file IROperator.h.
References Halide::Internal::IRHandle::as(), cast(), Halide::Internal::IntrusivePtr< T >::defined(), Halide::Type::element_of(), Halide::Type::is_scalar(), Halide::Type::is_vector(), Halide::Internal::Cast::make(), Halide::Internal::Broadcast::make(), Halide::Expr::type(), and Halide::Type::width.
Expr Halide::operator+ (Expr a, Expr b) inline
Return the sum of two expressions, doing any necessary type coercion using Internal::match_types.
Definition at line 145 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Add::make(), and Halide::Internal::match_types().
Expr& Halide::operator+= (Expr & a, Expr b) inline
Modify the first expression to be the sum of two expressions, without changing its type.
This casts the second argument to match the type of the first.
Definition at line 154 of file IROperator.h.
References cast(), Halide::Internal::IntrusivePtr< T >::defined(), and Halide::Internal::Add::make().
Expr Halide::operator- (Expr a, Expr b) inline
Return the difference of two expressions, doing any necessary type coercion using Internal::match_types.
Definition at line 162 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Sub::make(), and Halide::Internal::match_types().
Expr Halide::operator- (Expr a) inline
Return the negative of the argument.
Does no type casting, so more formally: return that number which when added to the original, yields zero of the same type. For unsigned integers the negative is still an unsigned integer. E.g. in UInt(8), the negative of 56 is 200, because 56 + 200 == 0
Definition at line 173 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Sub::make(), Halide::Internal::make_zero(), and Halide::Expr::type().
Expr& Halide::operator-= (Expr & a, Expr b) inline
Modify the first expression to be the difference of two expressions, without changing its type.
This casts the second argument to match the type of the first.
Definition at line 181 of file IROperator.h.
References cast(), Halide::Internal::IntrusivePtr< T >::defined(), and Halide::Internal::Sub::make().
Expr Halide::operator* (Expr a, Expr b) inline
Return the product of two expressions, doing any necessary type coercion using Internal::match_types.
Definition at line 189 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Mul::make(), and Halide::Internal::match_types().
Expr& Halide::operator*= (Expr & a, Expr b) inline
Modify the first expression to be the product of two expressions, without changing its type.
This casts the second argument to match the type of the first.
Definition at line 198 of file IROperator.h.
References cast(), Halide::Internal::IntrusivePtr< T >::defined(), and Halide::Internal::Mul::make().
Expr Halide::operator/ (Expr a, Expr b) inline
Return the ratio of two expressions, doing any necessary type coercion using Internal::match_types.
Definition at line 206 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Div::make(), and Halide::Internal::match_types().
Expr& Halide::operator/= (Expr & a, Expr b) inline
Modify the first expression to be the ratio of two expressions, without changing its type.
This casts the second argument to match the type of the first.
Definition at line 215 of file IROperator.h.
References cast(), Halide::Internal::IntrusivePtr< T >::defined(), and Halide::Internal::Div::make().
Expr Halide::operator% (Expr a, Expr b) inline
Return the first argument reduced modulo the second, doing any necessary type coercion using Internal::match_types.
Definition at line 223 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Mod::make(), and Halide::Internal::match_types().
Expr Halide::operator> (Expr a, Expr b) inline
Return a boolean expression that tests whether the first argument is greater than the second, after doing any necessary type coercion using Internal::match_types.
Definition at line 232 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::GT::make(), and Halide::Internal::match_types().
Expr Halide::operator< (Expr a, Expr b) inline
Return a boolean expression that tests whether the first argument is less than the second, after doing any necessary type coercion using Internal::match_types.
Definition at line 241 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::LT::make(), and Halide::Internal::match_types().
Expr Halide::operator<= (Expr a, Expr b) inline
Return a boolean expression that tests whether the first argument is less than or equal to the second, after doing any necessary type coercion using Internal::match_types.
Definition at line 250 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::LE::make(), and Halide::Internal::match_types().
Expr Halide::operator>= (Expr a, Expr b) inline
Return a boolean expression that tests whether the first argument is greater than or equal to the second, after doing any necessary type coercion using Internal::match_types.
Definition at line 260 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::GE::make(), and Halide::Internal::match_types().
Expr Halide::operator== (Expr a, Expr b) inline
Return a boolean expression that tests whether the first argument is equal to the second, after doing any necessary type coercion using Internal::match_types.
Definition at line 269 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::EQ::make(), and Halide::Internal::match_types().
Expr Halide::operator!= (Expr a, Expr b) inline
Return a boolean expression that tests whether the first argument is not equal to the second, after doing any necessary type coercion using Internal::match_types.
Definition at line 278 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::NE::make(), and Halide::Internal::match_types().
Expr Halide::operator&& (Expr a, Expr b) inline
Returns the logical and of the two arguments.
Definition at line 285 of file IROperator.h.
References Halide::Internal::And::make().
Expr Halide::operator|| (Expr a, Expr b) inline
Returns the logical or of the two arguments.
Definition at line 290 of file IROperator.h.
References Halide::Internal::Or::make().
Expr Halide::operator! (Expr a) inline
Returns the logical not the argument.
Definition at line 295 of file IROperator.h.
References Halide::Internal::Not::make().
Expr Halide::max (Expr a, Expr b) inline
Returns an expression representing the greater of the two arguments, after doing any necessary type coercion using Internal::match_types.
Definition at line 302 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Max::make(), and Halide::Internal::match_types().
Expr Halide::min (Expr a, Expr b) inline
Returns an expression representing the lesser of the two arguments, after doing any necessary type coercion using Internal::match_types.
Definition at line 311 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Min::make(), and Halide::Internal::match_types().
Referenced by Halide::Internal::Realize::make().
Expr Halide::clamp (Expr a, Expr min_val, Expr max_val) inline
Clamps an expression to lie within the given bounds.
The bounds are type-cast to match the expression.
Definition at line 319 of file IROperator.h.
References cast(), Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Min::make(), Halide::Internal::Max::make(), and Halide::Expr::type().
Expr Halide::abs (Expr a) inline
Returns the absolute value of a signed integer or floating-point expression.
Definition at line 329 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Int(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::select (Expr a, Expr b, Expr c) inline
Returns an expression equivalent to the ternary operator in C.
If the first argument is true, then return the second, else return the third.
Definition at line 350 of file IROperator.h.
References Halide::Internal::Select::make().
Expr Halide::sin (Expr x) inline
Return the sine of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 356 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::asin (Expr x) inline
Return the arcsine of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 367 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::cos (Expr x) inline
Return the cosine of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 378 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::acos (Expr x) inline
Return the arccosine of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 389 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::tan (Expr x) inline
Return the tangent of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 400 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::atan (Expr x) inline
Return the arctangent of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 411 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::sinh (Expr x) inline
Return the hyperbolic sine of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 422 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::asinh (Expr x) inline
Return the hyperbolic arcsinhe of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 433 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::cosh (Expr x) inline
Return the hyperbolic cosine of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 444 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::acosh (Expr x) inline
Return the hyperbolic arccosine of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 455 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::tanh (Expr x) inline
Return the hyperbolic tangent of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 466 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::atanh (Expr x) inline
Return the hyperbolic arctangent of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 477 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::sqrt (Expr x) inline
Return the square root of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 488 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::hypot (Expr x, Expr y) inline
Return the square root of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 499 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::exp (Expr x) inline
Return the exponential of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 513 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::log (Expr x) inline
Return the logarithm of a floating-point expression.
If the argument is not floating-point, is it cast to Float(32).
Definition at line 524 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::floor (Expr x) inline
Return the greatest whole number less than or equal to a floating-point expression.
If the argument is not floating-point, is it cast to Float(32). The return value is still in floating point, despite being a whole number.
Definition at line 537 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Referenced by Halide::Internal::mod_imp< double >().
Expr Halide::ceil (Expr x) inline
Return the least whole number greater than or equal to a floating-point expression.
If the argument is not floating-point, is it cast to Float(32). The return value is still in floating point, despite being a whole number.
Definition at line 550 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::round (Expr x) inline
Return the whole number closest to a floating-point expression.
If the argument is not floating-point, is it cast to Float(32). The return value is still in floating point, despite being a whole number. On ties, we round up.
Definition at line 563 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
Expr Halide::pow (Expr x, Expr y) inline
Return one floating point expression raised to the power of another.
The type of the result is given by the type of the first argument. If the first argument is not a floating-point type, it is cast to Float(32)
Definition at line 576 of file IROperator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Float(), Halide::Internal::Call::make(), Halide::Expr::type(), and Halide::Internal::vec().
std::ostream& Halide::operator<< (std::ostream & stream, Expr)
Emit an expression on an output stream (such as std::cout) in a human-readable form.
std::ostream& Halide::operator<< (std::ostream & stream, Type)
Emit a halide type on an output stream (such as std::cout) in a human-readable form.
Func Halide::lambda (Expr e) inline
Create a zero-dimensional halide function that returns the given expression.
The function may have more dimensions if the expression contains implicit arguments.
Definition at line 17 of file Lambda.h.
References Halide::Internal::unique_name().
Func Halide::lambda (Var x, Expr e) inline
Create a 1-D halide function in the first argument that returns the second argument.
The function may have more dimensions if the expression contains implicit arguments.
Definition at line 26 of file Lambda.h.
References Halide::Internal::unique_name().
Func Halide::lambda (Var x, Var y, Expr e) inline
Create a 2-D halide function in the first two arguments that returns the last argument.
The function may have more dimensions if the expression contains implicit arguments.
Definition at line 35 of file Lambda.h.
References Halide::Internal::unique_name().
Func Halide::lambda (Var x, Var y, Var z, Expr e) inline
Create a 3-D halide function in the first three arguments that returns the last argument.
The function may have more dimensions if the expression contains implicit arguments.
Definition at line 44 of file Lambda.h.
References Halide::Internal::unique_name().
Func Halide::lambda (Var x, Var y, Var z, Var w, Expr e) inline
Create a 4-D halide function in the first four arguments that returns the last argument.
The function may have more dimensions if the expression contains implicit arguments.
Definition at line 53 of file Lambda.h.
References Halide::Internal::unique_name().
std::ostream& Halide::operator<< (std::ostream & stream, RVar)
Emit an RVar in a human-readable form.
std::ostream& Halide::operator<< (std::ostream & stream, RDom)
Emit an RDom in a human-readable form.
Type Halide::Int (int bits, int width = 1) inline
Constructing a signed integer type.
Definition at line 76 of file Type.h.
References Halide::Type::bits, Halide::Type::Int, Halide::Type::t, and Halide::Type::width.
Referenced by abs(), Halide::ImageParam::extent(), Halide::Internal::IntImm::make(), Halide::Var::operator Expr(), Halide::ImageParam::stride(), type_of< char >(), type_of< int >(), type_of< short >(), and type_of< signed char >().
Type Halide::UInt (int bits, int width = 1) inline
Constructing an unsigned integer type.
Definition at line 85 of file Type.h.
References Halide::Type::bits, Halide::Type::t, Halide::Type::UInt, and Halide::Type::width.
Referenced by Bool(), type_of< unsigned char >(), type_of< unsigned int >(), and type_of< unsigned short >().
Type Halide::Float (int bits, int width = 1) inline
Construct a floating-point type.
Definition at line 94 of file Type.h.
References Halide::Type::bits, Halide::Type::Float, Halide::Type::t, and Halide::Type::width.
Referenced by abs(), acos(), acosh(), asin(), asinh(), atan(), atanh(), ceil(), cos(), cosh(), exp(), floor(), hypot(), log(), Halide::Internal::FloatImm::make(), pow(), round(), sin(), sinh(), sqrt(), tan(), tanh(), type_of< double >(), and type_of< float >().
Type Halide::Bool (int width = 1) inline
Construct a boolean type.
Definition at line 103 of file Type.h.
References UInt().
Referenced by Halide::Internal::EQ::make(), Halide::Internal::NE::make(), Halide::Internal::LT::make(), Halide::Internal::LE::make(), Halide::Internal::GT::make(), Halide::Internal::GE::make(), Halide::Internal::And::make(), Halide::Internal::Or::make(), Halide::Internal::Not::make(), and type_of< bool >().
template<typename T > Type Halide::type_of ()
Construct the halide equivalent of a C type.
template<> Type Halide::type_of< float > () inline
Definition at line 110 of file Type.h.
References Float().
template<> Type Halide::type_of< double > () inline
Definition at line 111 of file Type.h.
References Float().
template<> Type Halide::type_of< unsigned char > () inline
Definition at line 112 of file Type.h.
References UInt().
template<> Type Halide::type_of< unsigned short > () inline
Definition at line 113 of file Type.h.
References UInt().
template<> Type Halide::type_of< unsigned int > () inline
Definition at line 114 of file Type.h.
References UInt().
template<> Type Halide::type_of< bool > () inline
Definition at line 115 of file Type.h.
References Bool().
template<> Type Halide::type_of< char > () inline
Definition at line 116 of file Type.h.
References Int().
template<> Type Halide::type_of< short > () inline
Definition at line 117 of file Type.h.
References Int().
template<> Type Halide::type_of< int > () inline
Definition at line 118 of file Type.h.
References Int().
template<> Type Halide::type_of< signed char > () inline
Definition at line 119 of file Type.h.
References Int().