Halide: Halide::Internal::Realize Struct Reference
Halide::Internal::Realize Struct Reference
Allocate a multi-dimensional buffer of the given type and size.
#include <IR.h>
Inherits Halide::Internal::StmtNode< Realize >.
Static Public Member Functions
static Stmt make (std::string name, Type type, const Region &bounds, Stmt body)
Public Attributes
std::string name
Type type
Region bounds
Stmt body
Additional Inherited Members
Public Member Functions inherited from Halide::Internal::StmtNode< Realize >
void accept (IRVisitor *v) const
We use the visitor pattern to traverse IR nodes throughout the compiler, so we have a virtual accept method which accepts visitors.
virtual IRNodeType * type_info () const
Each IR node subclass should return some unique pointer.
Static Public Attributes inherited from Halide::Internal::StmtNode< Realize >
static EXPORT IRNodeType _type_info
Detailed Description
Allocate a multi-dimensional buffer of the given type and size.
Create some scratch memory that will back the function 'name' over the range specified in 'bounds'. The bounds are a vector of (min, extent) pairs for each dimension.
Definition at line 804 of file IR.h.
Member Function Documentation
static Stmt Halide::Internal::Realize::make (std::string name, Type type, const Region & bounds, Stmt body) inline static
Definition at line 810 of file IR.h.
References body, bounds, Halide::Internal::IntrusivePtr< T >::defined(), Halide::Type::is_scalar(), Halide::min(), name, Halide::Expr::type(), and type.
Member Data Documentation
std::string Halide::Internal::Realize::name
Definition at line 805 of file IR.h.
Referenced by make().
Type Halide::Internal::Realize::type
Definition at line 806 of file IR.h.
Referenced by make().
Region Halide::Internal::Realize::bounds
Definition at line 807 of file IR.h.
Referenced by make().
Stmt Halide::Internal::Realize::body
Definition at line 808 of file IR.h.
Referenced by make().
The documentation for this struct was generated from the following file:
IR.h