Halide: Halide::Internal::Call Struct Reference
Halide::Internal::Call Struct Reference
A function call.
#include <IR.h>
Inherits Halide::Internal::ExprNode< Call >.
Public Types
enum CallType { Image, Extern, Halide }
Static Public Member Functions
static Expr make (Type type, std::string name, const std::vector< Expr > &args, CallType call_type, Function func, Buffer image, Parameter param)
static Expr make (Type type, std::string name, const std::vector< Expr > &args)
Convenience constructor for calls to externally defined functions.
static Expr make (Function func, const std::vector< Expr > &args)
Convenience constructor for calls to other halide functions.
static Expr make (Buffer image, const std::vector< Expr > &args)
Convenience constructor for loads from concrete images.
static Expr make (Parameter param, const std::vector< Expr > &args)
Convenience constructor for loads from images parameters.
Public Attributes
std::string name
std::vector< Expr > args
CallType call_type
Function func
Buffer image
Parameter param
Additional Inherited Members
Public Member Functions inherited from Halide::Internal::ExprNode< Call >
void accept (IRVisitor *v) const
We use the visitor pattern to traverse IR nodes throughout the compiler, so we have a virtual accept method which accepts visitors.
virtual IRNodeType * type_info () const
Each IR node subclass should return some unique pointer.
Static Public Attributes inherited from Halide::Internal::ExprNode< Call >
static EXPORT IRNodeType _type_info
Detailed Description
A function call.
This can represent a call to some extern function (like sin), but it's also our multi-dimensional version of a Load, so it can be a load from an input image, or a call to another halide function. The latter two types of call nodes don't survive all the way down to code generation - the lowering process converts them to Load nodes.
Definition at line 861 of file IR.h.
Member Enumeration Documentation
enum Halide::Internal::Call::CallType
Enumerator
Image
Extern
Halide
Definition at line 864 of file IR.h.
Member Function Documentation
static Expr Halide::Internal::Call::make (Type type, std::string name, const std::vector< Expr > & args, CallType call_type, Function func, Buffer image, Parameter param) inline static
Definition at line 879 of file IR.h.
References Halide::Internal::Function::args(), args, call_type, Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::Parameter::defined(), Halide::Buffer::defined(), func, Halide, image, name, param, Halide::Internal::BaseExprNode::type, and Halide::Internal::Function::value().
Referenced by Halide::abs(), Halide::acos(), Halide::acosh(), Halide::asin(), Halide::asinh(), Halide::atan(), Halide::atanh(), Halide::ceil(), Halide::cos(), Halide::cosh(), Halide::exp(), Halide::floor(), Halide::hypot(), Halide::log(), make(), Halide::Image< T >::operator()(), Halide::ImageParam::operator()(), Halide::pow(), Halide::round(), Halide::sin(), Halide::sinh(), Halide::sqrt(), Halide::tan(), and Halide::tanh().
static Expr Halide::Internal::Call::make (Type type, std::string name, const std::vector< Expr > & args) inline static
Convenience constructor for calls to externally defined functions.
Definition at line 903 of file IR.h.
References Extern, and make().
static Expr Halide::Internal::Call::make (Function func, const std::vector< Expr > & args) inline static
Convenience constructor for calls to other halide functions.
Definition at line 908 of file IR.h.
References args, Halide::Internal::IntrusivePtr< T >::defined(), func, Halide, make(), Halide::Internal::Function::name(), Halide::Expr::type(), and Halide::Internal::Function::value().
static Expr Halide::Internal::Call::make (Buffer image, const std::vector< Expr > & args) inline static
Convenience constructor for loads from concrete images.
Definition at line 914 of file IR.h.
References args, Image, image, make(), Halide::Buffer::name(), and Halide::Buffer::type().
static Expr Halide::Internal::Call::make (Parameter param, const std::vector< Expr > & args) inline static
Convenience constructor for loads from images parameters.
Definition at line 919 of file IR.h.
References args, Image, make(), Halide::Internal::Parameter::name(), param, and Halide::Internal::Parameter::type().
Member Data Documentation
std::string Halide::Internal::Call::name
Definition at line 862 of file IR.h.
Referenced by make().
std::vector<Expr> Halide::Internal::Call::args
Definition at line 863 of file IR.h.
Referenced by make().
CallType Halide::Internal::Call::call_type
Definition at line 865 of file IR.h.
Referenced by make().
Function Halide::Internal::Call::func
Definition at line 869 of file IR.h.
Referenced by make().
Buffer Halide::Internal::Call::image
Definition at line 873 of file IR.h.
Referenced by make().
Parameter Halide::Internal::Call::param
Definition at line 877 of file IR.h.
Referenced by make().
The documentation for this struct was generated from the following file:
IR.h